name: GromTable
description: A sample Polymer application
dependencies:
    polymer: any
    intl: any
    cookie: 0.0.4
    serialization: any
transformers:
- polymer:
    entry_points:
    - web/index.html
    - web/testuser.html
    - web/admin.html

